# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_auto_20171204_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='texts',
            field=models.TextField(),
        ),
    ]
