# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20171204_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='images',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='images',
            field=models.ManyToManyField(to='frontpage.Image'),
        ),
    ]
