# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_auto_20171204_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='age',
            field=models.ManyToManyField(to='frontpage.Age'),
        ),
    ]
