# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0008_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='education',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='income',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
