# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_auto_20180103_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='gender',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='gender',
            field=models.ManyToManyField(to='frontpage.Gender'),
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='income',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='education',
            field=models.ManyToManyField(to='frontpage.Education'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='ethnicity',
            field=models.ManyToManyField(to='frontpage.Ethnicity'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='income',
            field=models.ManyToManyField(to='frontpage.Income'),
        ),
    ]
