# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0013_auto_20180117_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='religion',
            field=models.ManyToManyField(to='frontpage.Religion'),
        ),
    ]
